<?php
/**
 * Created by PhpStorm.
 * User: Will
 * Date: 5/29/2018
 * Time: 9:50 AM
 */

use PHPUnit\Framework\TestCase;

class SomeClassTest extends TestCase
{
	protected function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
	}
	
	public function testCanBeCreatedFromValidEmailAddress()
	{
		$this->assertInstanceOf(
			\App\Mail::class,
			\App\Mail::send('user@example.com', 'Test Message', 'Test text', '<p>test html</p>' )
		);
	}
}
